### ISSUE TITLE
Aligner les éléments du menu d'en-haut vers la droite.

### ISSUE THREAD

**Issue by Ishixe** [Ishixe/TechnologiesProjet1#2]

**Comment by MaximeSauvage1** [comment]
Salut @Ishixe !

Je cherche à faire ma première contribution dans le monde du libre et je suis tombé sur ton projet.
Je peux te proposer une solution à ce problème.
Je peux te proposer une Pull Request?

**Comment by Ishixe** [comment]
Salut @MaximeSauvage1  !

Désolé du retard, je viens de voir ton message. Nous sommes actuellement 3 personnes qui travaillons sur un projet d'école. Comme tu peux le constater, nos documents sont en constantes modifications, mais je serais intéressé à connaître ta solution par curiosité! Alors ne te gêne pas pour proposer quoi que ce soit :)
