### ISSUE TITLE
Rendre un bouton "actif" de la même couleur que le hover (blanc)

### ISSUE THREAD

**Issue by katebeaud** [Ishixe/TechnologiesProjet1#3]
Afin de savoir sur quel page l'utilisateur se retrouve nous devons créer l'effet

**Comment by Ishixe** [comment]
Effet ajout, reste plus qu'à corriger les Hover à partir du javascript, je pense m'orienter vers cette solution : https://plnkr.co/edit/LzjkY8WIv8IF2P3YEGMk?p=preview qui modifie la classe de l'élément sélectionné et qui évite d'écraser le CSS existant!

**Comment by Ishixe** [comment]
J'ai utilisé des fonctions javascript au final. Moins compliqué!
