### ISSUE TITLE
Créer une barre de recherche pour la liste de contacts

### ISSUE THREAD

**Issue by katebeaud** [Ishixe/TechnologiesProjet1#4]
Ainsi que la liste de contacts en tant que tel :)

**Comment by Ishixe** [comment]
Je pense que cette fonction va prendre la poubelle pour la partie 1, mais c'est quelque chose que j'aimerais vraiment intégrer par après. Ton opinion sur le sujet?

**Comment by katebeaud** [comment]
Je pense aussi mettre de côté la barre de recherche. Ce n'est effectivement pas nécessaire pour le projet 1.

**Comment by Ishixe** [comment]
Done!
